// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace TipanJ_ExamenProgreso1.Migrations
{
    [DbContext(typeof(TipanJbd))]
    [Migration("20250429131612_Agrega modelos de datos")]
    partial class Agregamodelosdedatos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TipanJ_ExamenProgreso1.Models.Cliente", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(8)
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCliente"));

                    b.Property<bool>("DescuentorPorRecomendacion")
                        .HasColumnType("bit");

                    b.Property<int>("DiasHospedaje")
                        .HasMaxLength(4)
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaDeNacimiento")
                        .HasMaxLength(4)
                        .HasColumnType("datetime2");

                    b.Property<int>("IdReserva")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<float>("PuntuacionServicio")
                        .HasColumnType("real");

                    b.HasKey("IdCliente");

                    b.HasIndex("IdReserva");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("TipanJ_ExamenProgreso1.Models.Recompensa", b =>
                {
                    b.Property<int>("IdRecompensa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRecompensa"));

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PuntosAcumulados")
                        .HasColumnType("int");

                    b.Property<string>("TipoDeRecompensa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdRecompensa");

                    b.ToTable("Recompensa");
                });

            modelBuilder.Entity("TipanJ_ExamenProgreso1.Models.Reserva", b =>
                {
                    b.Property<int>("IdReserva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdReserva"));

                    b.Property<DateTime>("FechaEntrada")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaSalida")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdRecompensa")
                        .HasColumnType("int");

                    b.Property<string>("InformacionCliente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("valorPagar")
                        .HasColumnType("bit");

                    b.HasKey("IdReserva");

                    b.HasIndex("IdRecompensa");

                    b.ToTable("Reserva");
                });

            modelBuilder.Entity("TipanJ_ExamenProgreso1.Models.Cliente", b =>
                {
                    b.HasOne("TipanJ_ExamenProgreso1.Models.Reserva", "Reserva")
                        .WithMany()
                        .HasForeignKey("IdReserva")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reserva");
                });

            modelBuilder.Entity("TipanJ_ExamenProgreso1.Models.Reserva", b =>
                {
                    b.HasOne("TipanJ_ExamenProgreso1.Models.Recompensa", "Recompensa")
                        .WithMany()
                        .HasForeignKey("IdRecompensa");

                    b.Navigation("Recompensa");
                });
#pragma warning restore 612, 618
        }
    }
}
